In [8]:
import pandas as pd

In [9]:
wt = pd.read_csv("popular_cities_weather.csv")

In [10]:
wt = wt.fillna(wt.mean(numeric_only=True))

In [11]:
wt.isnull().sum()

date       0
tavg       0
tmin       0
tmax       0
prcp       0
wspd    7056
pres       0
tsun       0
city       0
dtype: int64

In [12]:
tot_null = wt.isnull().sum()/100

In [13]:
valid_columns = wt.columns[tot_null < 50]

In [14]:
wt.drop(columns=["wspd"], inplace=True)

In [15]:
wt = wt.dropna()

In [16]:
wt["tavg"] = wt["tavg"].fillna(wt["tavg"].mean())

In [17]:
wt["tsun"] = wt["tsun"].fillna(wt["tsun"].mean()) 
wt

,date,tavg,tmin,tmax,prcp,pres,tsun,city
0,2020-01-01 00:00:00,24.9,19.2,29.9,0.0,1013.4,13800.000000,Mumbai
1,2020-02-01 00:00:00,27.3,21.0,32.6,0.0,1012.7,11220.000000,Mumbai
2,2020-03-01 00:00:00,27.7,22.6,31.9,0.0,1011.2,12900.000000,Mumbai
3,2020-04-01 00:00:00,30.2,26.4,33.9,0.0,1009.6,14220.000000,Mumbai
4,2020-05-01 00:00:00,31.1,28.6,34.0,0.0,1007.3,15960.000000,Mumbai
...,...,...,...,...,...,...,...,...
7051,2025-08-01 00:00:00,20.8,18.0,24.8,321.1,1007.4,10584.997921,Shimla
7052,2025-09-01 00:00:00,19.8,16.3,24.3,150.9,1009.4,10584.997921,Shimla
7053,2025-10-01 00:00:00,15.9,10.6,22.6,61.5,1015.1,10584.997921,Shimla
7054,2025-11-01 00:00:00,11.6,6.1,19.4,2.4,1017.8,10584.997921,Shimla
7055,2025-12-01 00:00:00,10.9,6.4,18.3,0.0,1017.9,10584.997921,Shimla

In [18]:
wt.index

RangeIndex(start=0, stop=7056, step=1)

In [19]:
wt["date"] = pd.to_datetime(wt["date"])

In [20]:
wt["year"] = wt["date"].dt.year

In [21]:
wt["month"] = wt["date"].dt.month

In [22]:
from sklearn.preprocessing import LabelEncoder   #label encoder converts text label to num


le = LabelEncoder()

wt["city"] = le.fit_transform(wt["city"])  #fit -> Learns Data  , transform -> covert into numbers

In [23]:
wt["city"].unique()

array([62, 24, 11,  1, 36, 19, 51, 71, 39, 82, 54, 48, 63, 69, 37, 83, 15,
       94, 90, 28, 55, 73,  0, 79, 65, 27, 68, 60, 47, 92, 91, 81, 25, 46,
        7, 72,  5, 20, 38, 35, 93, 56, 34, 18,  8, 61, 33,  4, 80, 74, 40,
       85, 16, 77, 95, 84, 14, 76, 32,  6, 17, 67, 44, 13, 21, 29, 49, 66,
       12, 23, 26,  9, 75, 64, 50,  2,  3, 31, 43, 89, 53, 45, 70, 42, 10,
       59, 86, 58, 30, 41, 88, 57, 87, 22, 52, 78])

In [24]:
X = wt[["month", "city", "prcp", "pres", "tsun"]]   #columns(features) selected

In [25]:
y = wt["tavg"]

In [26]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split ( X , y , test_size=0.2 , random_state=42
, shuffle=True)

In [27]:
wt

,date,tavg,tmin,tmax,prcp,pres,tsun,city,year,month
0,2020-01-01,24.9,19.2,29.9,0.0,1013.4,13800.000000,62,2020,1
1,2020-02-01,27.3,21.0,32.6,0.0,1012.7,11220.000000,62,2020,2
2,2020-03-01,27.7,22.6,31.9,0.0,1011.2,12900.000000,62,2020,3
3,2020-04-01,30.2,26.4,33.9,0.0,1009.6,14220.000000,62,2020,4
4,2020-05-01,31.1,28.6,34.0,0.0,1007.3,15960.000000,62,2020,5
...,...,...,...,...,...,...,...,...,...,...
7051,2025-08-01,20.8,18.0,24.8,321.1,1007.4,10584.997921,78,2025,8
7052,2025-09-01,19.8,16.3,24.3,150.9,1009.4,10584.997921,78,2025,9
7053,2025-10-01,15.9,10.6,22.6,61.5,1015.1,10584.997921,78,2025,10
7054,2025-11-01,11.6,6.1,19.4,2.4,1017.8,10584.997921,78,2025,11
7055,2025-12-01,10.9,6.4,18.3,0.0,1017.9,10584.997921,78,2025,12

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
model = LinearRegression()

In [30]:
model.fit(X_train , y_train)

LinearRegression()

In [31]:
y_pred = model.predict(X_test)

In [32]:
from sklearn.metrics import mean_absolute_error, r2_score

print(mean_absolute_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

2.196387127850957
0.6861361106195776

In [33]:
r2 = r2_score(y_test, y_pred)

print(r2)

0.6861361106195776

In [37]:
print(y_test.head())
print(y_pred[:5])

1835    15.5
5559    31.2
6792    22.8
970     22.1
6808    28.7
Name: tavg, dtype: float64
[20.07437539 26.17346349 22.53803883 23.30340747 24.92585607]

In [38]:
import joblib

joblib.dump(model, "weather_model.pkl")
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']